apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: knative-functions-data
  namespace: knative-functions-demo
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi