apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: serverless-orders
  namespace: bobbycar
  labels:
    strimzi.io/cluster: bobbycar-cluster
spec:
  config:
    retention.ms: 60000
    segment.bytes: 1073741824
  partitions: 1
  replicas: 1
  topicName: serverless-orders
